### ISSUE TITLE
Scraper pakt maar 1 advertentie

### ISSUE THREAD

**Issue by Dharquen** [jensjeflensje/marktplaats-scraper-tool#1]
Jouw scraper is heel elegant, zeker vergeleken met andere Marktplaats scrapers die ik heb gevonden.
Het enige probleem is dat de scraper maar 1 advertentie pak, per keer.
Ik zie niet meteen waar het mis gaat, zou je mij hier een handje mee kunnen helpen?

**Comment by jensjeflensje** [comment]
Hi Dharquen, bedankt! Ik zal er gelijk eens naar kijken!

**Comment by Dharquen** [comment]
Super, dat zou geweldig zijn!

**Comment by jensjeflensje** [comment]
Hi, ik neem aan dat je test.py uitvoert? In dat bestand wordt handmatig een limiet van 1 gezet. Kijk maar:

```
#------------------------------------------------------------------------------HIER-----------
Marktplaats("fiets", zip="1016LV", distance=10000, pricefrom=0, priceto=100, limit=1, offset=0)
```

Ik krijg namelijk, als ik dat limiet verander, gewoon meerdere advertenties :)

**Comment by Dharquen** [comment]
Ah, heerlijk simpel.
Daar had ik strak overheen gekeken! 
Dank je.

**Comment by jensjeflensje** [comment]
Top!
