### ISSUE TITLE
sort order

### ISSUE THREAD

**Issue by wietze314** [jensjeflensje/marktplaats-scraper-tool#2]
Ik gebruik de scraper maar krijg het niet voor elkaar om de sorteer volgorde te wijzigen. 
Bijvoorbeeld:

https://www.marktplaats.nl/lrp/api/search/?query=pokemon&postcode=2513AA&distanceMeters=5000&sortBy=PRICE&sortOrder=INCREASING

werkt, maar niet als ik het toe probeer te voegen aan de request in het python script:

```
self.request = requests.get(
            "https://www.marktplaats.nl/lrp/api/search",
            params={
                "attributeRanges[]":  [
                    f"PriceCents:{pricefrom * 100}:{priceto * 100}",
                ],
                "limit": str(limit),
                "offset": str(offset),
                "query": str(query),
                "searchInTitleAndDescription": "true",
                "viewOptions": "list-view",
                "distanceMeters": str(distance),
                "postcode": zip,
                "sortBy": "PRICE",
                "sortOrder":"INCREASING"             
            },
```

**Comment by jensjeflensje** [comment]
Hey Wietze, eigenlijk is deze scraper tool een beetje Depricated. Ik ga verder met ontwikkelen in https://github.com/jensjeflensje/marktplaats-py

Als je daar een issue wilt maken, kan ik kijken of we het misschien toe kunnen voegen. Een PR is natuurlijk ook welkom :)

**Comment by wietze314** [comment]
Bedankt, ik kwam erachter dat het op zich wel lukt, maar dat ik niet had begrepen dat bij een update van de bron, een import de cache niet ververst.

Ik zal in het vervolg het andere project gebruiken!

Was nog wel op zoek naar een mogelijkheid om niet een search te doen, maar gewoon alle advertenties van een categoryId. Als je daar iets op weet, ben ik erg benieuwd.
